# Generated by Django 4.0.6 on 2022-08-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='material',
            field=models.TextField(default='material'),
        ),
    ]
