# Generated by Django 4.0.6 on 2022-08-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0003_food_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.TextField(default='img'),
        ),
        migrations.AddField(
            model_name='food',
            name='imgfile',
            field=models.TextField(default='imgfile'),
        ),
        migrations.AddField(
            model_name='food',
            name='nutrition',
            field=models.TextField(default='nutrition'),
        ),
    ]
