# Generated by Django 4.0.6 on 2022-08-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0005_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
