# Generated by Django 4.0.6 on 2022-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0006_alter_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='food_id',
            field=models.IntegerField(),
        ),
    ]
