# Generated by Django 4.0.6 on 2022-08-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapi', '0007_alter_wishlist_food_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user_uid',
        ),
    ]
